export enum Suit {
  HEARTS = 'HEARTS',
  DIAMONDS = 'DIAMONDS',
  CLUBS = 'CLUBS',
  SPADES = 'SPADES',
  JOKER = 'JOKER'
}

export enum CardValue {
  ACE = 'A',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9',
  TEN = '10',
  JACK = 'J',
  QUEEN = 'Q',
  KING = 'K',
  JOKER = 'JOKER'
}

export enum RuleType {
  GAME = 'GAME',    // Interactive game (e.g., Categories)
  ACTION = 'ACTION', // Immediate action (e.g., Drink)
  PASSIVE = 'PASSIVE', // Ongoing rule (e.g., Mate)
  AI = 'AI'         // Generated by Gemini
}

export interface CardRule {
  title: string;
  description: string;
  type: RuleType;
}

export interface Card {
  suit: Suit;
  value: CardValue;
  id: string; // unique identifier for React keys
  isRed: boolean;
}

export interface AIChallengeResponse {
  title: string;
  description: string;
  intensity: 'Low' | 'Medium' | 'High';
}
